import type { Player } from '@/types/player';
import type { Visit } from '@/types/visit';
import type { Alert } from '@/types/alert';
import type { Match } from '@/types/match';

// ─── Demo Players ────────────────────────────────────────────────────────────

export const DEMO_PLAYERS: Player[] = [
  {
    id: 'demo-1',
    name: 'Carlos Vega Hernández',
    birthDate: '2000-03-15',
    position: 'Delantero Centro',
    foot: 'derecho',
    height: 183,
    weight: 78,
    club: 'Sevilla FC B',
    city: 'Sevilla',
    category: 'Segunda RFEF',
    division: 'Segunda RFEF Grupo IV',
    status: 'activo',
    tags: ['gol', 'velocidad', 'aéreo'],
    privateNotes:
      'Delantero con excelente remate de cabeza y gran arranque en velocidad. Buen movimiento en el área. Necesita mejorar en el juego de espaldas y la retención bajo presión. Muy buen carácter competitivo.',
    photo: '',
    metrics: { technical: 8, tactical: 7, physical: 8, attitude: 9 },
    cvClubs: [
      { club: 'Sevilla FC B', etapa: '2022–actualidad', categoria: 'Segunda RFEF' },
      { club: 'Sevilla FC Juvenil A', etapa: '2020–2022', categoria: 'División de Honor Juvenil' },
    ],
    createdAt: '2024-10-01T10:00:00Z',
    updatedAt: '2025-03-15T18:30:00Z',
    userId: 'demo',
  },
  {
    id: 'demo-2',
    name: 'Diego Morales Castillo',
    birthDate: '1999-07-22',
    position: 'Mediocentro',
    foot: 'ambos',
    height: 178,
    weight: 73,
    club: 'Atlético Baleares',
    city: 'Palma',
    category: 'Primera RFEF',
    division: 'Primera RFEF Grupo II',
    status: 'seguimiento',
    tags: ['visión', 'pases', 'liderazgo'],
    privateNotes:
      'Mediocentro de enorme calidad técnica. Domina el juego en corto y en largo con una visión espacial privilegiada. Ambidiestro de facto. Físicamente puede mejorar. Interés confirmado de dos clubs de Segunda.',
    photo: '',
    metrics: { technical: 9, tactical: 8, physical: 6, attitude: 8 },
    cvClubs: [
      { club: 'Atlético Baleares', etapa: '2021–actualidad', categoria: 'Primera RFEF' },
      { club: 'RCD Mallorca B', etapa: '2018–2021', categoria: 'Segunda RFEF' },
    ],
    createdAt: '2024-11-15T09:00:00Z',
    updatedAt: '2025-03-22T17:00:00Z',
    userId: 'demo',
  },
  {
    id: 'demo-3',
    name: 'Álex Ruano Pérez',
    birthDate: '2001-11-08',
    position: 'Lateral Derecho',
    foot: 'derecho',
    height: 176,
    weight: 70,
    club: 'RC Deportivo',
    city: 'La Coruña',
    category: 'Segunda División',
    division: 'Segunda División',
    status: 'activo',
    tags: ['subida', 'pressing', 'joven'],
    privateNotes:
      'Lateral muy vertical con gran capacidad de desborde. Defensivamente solvente para su edad. Muy buena anticipación y recuperación de balón. Perfil interesante para plantillas de Segunda.',
    photo: '',
    metrics: { technical: 7, tactical: 7, physical: 8, attitude: 9 },
    cvClubs: [
      { club: 'RC Deportivo', etapa: '2023–actualidad', categoria: 'Segunda División' },
      { club: 'RC Deportivo B', etapa: '2021–2023', categoria: 'Segunda RFEF' },
    ],
    createdAt: '2024-12-01T11:00:00Z',
    updatedAt: '2025-03-29T20:00:00Z',
    userId: 'demo',
  },
  {
    id: 'demo-4',
    name: 'Javier Soto Álvarez',
    birthDate: '1998-05-30',
    position: 'Central',
    foot: 'derecho',
    height: 189,
    weight: 84,
    club: 'CD Lugo',
    city: 'Lugo',
    category: 'Primera RFEF',
    division: 'Primera RFEF Grupo I',
    status: 'espera',
    tags: ['aéreo', 'físico', 'defensa'],
    privateNotes:
      'Central con gran presencia física y dominio en el juego aéreo. Irregular en la salida de balón — comete errores graves bajo presión. En espera de nueva visita antes del mercado de invierno.',
    photo: '',
    metrics: { technical: 6, tactical: 7, physical: 9, attitude: 7 },
    cvClubs: [
      { club: 'CD Lugo', etapa: '2020–actualidad', categoria: 'Primera RFEF' },
      { club: 'SD Ponferradina B', etapa: '2018–2020', categoria: 'Tercera División' },
    ],
    createdAt: '2025-01-10T08:00:00Z',
    updatedAt: '2025-03-08T19:00:00Z',
    userId: 'demo',
  },
  {
    id: 'demo-5',
    name: 'Sergio Linares García',
    birthDate: '2002-02-14',
    position: 'Extremo Izquierdo',
    foot: 'izquierdo',
    height: 174,
    weight: 67,
    club: 'Granada CF B',
    city: 'Granada',
    category: 'Segunda RFEF',
    division: 'Segunda RFEF Grupo IV',
    status: 'seguimiento',
    tags: ['velocidad', 'regate', 'joven'],
    privateNotes:
      'Extremo con desborde en velocidad brutal. Perfil similar a un falso nueve en ataque posicional. Solo 22 años y ya con nivel para Primera RFEF. Seguimiento prioritario antes de mercado de verano.',
    photo: '',
    metrics: { technical: 8, tactical: 5, physical: 8, attitude: 7 },
    cvClubs: [
      { club: 'Granada CF B', etapa: '2023–actualidad', categoria: 'Segunda RFEF' },
      { club: 'Granada CF Juvenil A', etapa: '2021–2023', categoria: 'División de Honor Juvenil' },
    ],
    createdAt: '2025-02-01T12:00:00Z',
    updatedAt: '2025-03-15T21:00:00Z',
    userId: 'demo',
  },
  {
    id: 'demo-6',
    name: 'Pablo Ferrán Molina',
    birthDate: '2000-09-03',
    position: 'Portero',
    foot: 'derecho',
    height: 188,
    weight: 82,
    club: 'Valencia CF Mestalla',
    city: 'Valencia',
    category: 'Segunda RFEF',
    division: 'Segunda RFEF Grupo III',
    status: 'descartado',
    tags: ['reacción', 'salidas'],
    privateNotes:
      'Descartado tras observar problemas de actitud reiterados en partido y entrenamiento. Buen perfil físico pero mentalidad incompatible con el proyecto. No encaja en los valores buscados.',
    photo: '',
    metrics: { technical: 6, tactical: 7, physical: 7, attitude: 4 },
    cvClubs: [
      { club: 'Valencia CF Mestalla', etapa: '2022–actualidad', categoria: 'Segunda RFEF' },
    ],
    createdAt: '2025-01-20T14:00:00Z',
    updatedAt: '2025-02-14T17:00:00Z',
    userId: 'demo',
  },
];

// ─── Demo Visits (keyed by player ID) ────────────────────────────────────────

export const DEMO_VISITS: Record<string, Visit[]> = {
  'demo-1': [
    {
      id: 'dv-1-1',
      fecha: '2025-03-15',
      partido: 'J28 · Sevilla FC B vs Recreativo Huelva',
      nota: 'Partido muy completo. Dos asistencias y presión constante en los 90\'. Buen remate de cabeza en el 67\' que se fue al palo. Muy activo sin balón.',
      valoracion: 8,
      createdAt: '2025-03-15T20:30:00Z',
    },
    {
      id: 'dv-1-2',
      fecha: '2025-02-22',
      partido: 'J23 · Sevilla FC B vs CD El Ejido',
      nota: 'Marcó el gol del empate en el 78\'. Desborde en velocidad por banda derecha. Algo errático en el pase final pero muy peligroso.',
      valoracion: 7,
      createdAt: '2025-02-22T21:00:00Z',
    },
    {
      id: 'dv-1-3',
      fecha: '2025-01-18',
      partido: 'J18 · Málaga CF vs Sevilla FC B',
      nota: 'Partido flojo del equipo. Vega trabajó mucho pero sin espacios. Buen comportamiento defensivo. Se mantiene activo incluso en días malos del equipo.',
      valoracion: 6,
      createdAt: '2025-01-18T21:00:00Z',
    },
    {
      id: 'dv-1-4',
      fecha: '2024-12-07',
      partido: 'J12 · Sevilla FC B vs Córdoba CF',
      nota: 'Primer vistazo. Muy interesante en velocidad y potencia. Necesita más visitas para confirmar regularidad. Gol anulado por fuera de juego milimétrico.',
      valoracion: 7,
      createdAt: '2024-12-07T20:00:00Z',
    },
  ],
  'demo-2': [
    {
      id: 'dv-2-1',
      fecha: '2025-03-22',
      partido: 'J30 · Atlético Baleares vs UD Ibiza',
      nota: 'Director de juego total. 94% de pases completados según datos del estadio. Liderazgo evidente desde el centro del campo. Mejor partido que le he visto.',
      valoracion: 9,
      createdAt: '2025-03-22T20:30:00Z',
    },
    {
      id: 'dv-2-2',
      fecha: '2025-02-08',
      partido: 'J22 · Linares Deportivo vs Atlético Baleares',
      nota: 'Algo incómodo fuera de casa ante el pressing rival. Perdió balones en zonas peligrosas. Pero su técnica es innegable incluso en un día irregular.',
      valoracion: 7,
      createdAt: '2025-02-08T21:00:00Z',
    },
    {
      id: 'dv-2-3',
      fecha: '2025-01-25',
      partido: 'Copa RFEF · Atlético Baleares vs Badajoz',
      nota: 'Salió al campo en el 60\'. Impacto inmediato con dos asistencias de gol en los últimos 30 minutos. Desequilibrio desde el banco.',
      valoracion: 8,
      createdAt: '2025-01-25T21:30:00Z',
    },
  ],
  'demo-3': [
    {
      id: 'dv-3-1',
      fecha: '2025-03-29',
      partido: 'J31 · RC Deportivo vs SD Ponferradina',
      nota: 'Lateral muy vertical en un Deportivo sólido. Tres centros peligrosos al área. Defensivamente solvente, ganó todos los duelos en su banda.',
      valoracion: 8,
      createdAt: '2025-03-29T21:00:00Z',
    },
    {
      id: 'dv-3-2',
      fecha: '2025-03-01',
      partido: 'J25 · CD Lugo vs RC Deportivo',
      nota: 'Buen partido individual en un empate a cero con el que Deportivo no estaba cómodo. Ruano fue de lo mejor en campo rival.',
      valoracion: 7,
      createdAt: '2025-03-01T21:00:00Z',
    },
    {
      id: 'dv-3-3',
      fecha: '2025-01-11',
      partido: 'J17 · RC Deportivo vs Racing de Ferrol',
      nota: 'Debut observación. Con 23 años tiene una madurez defensiva fuera de lo normal. Mucho potencial de crecimiento.',
      valoracion: 8,
      createdAt: '2025-01-11T20:30:00Z',
    },
  ],
  'demo-4': [
    {
      id: 'dv-4-1',
      fecha: '2025-03-08',
      partido: 'J26 · CD Lugo vs Sporting Gijón B',
      nota: 'Sólido en la zaga. Ganó todos los duelos aéreos. Falló en salida de balón ante pressing bien organizado. Pendiente de nueva visita.',
      valoracion: 7,
      createdAt: '2025-03-08T21:00:00Z',
    },
    {
      id: 'dv-4-2',
      fecha: '2025-01-30',
      partido: 'J19 · Racing de Ferrol vs CD Lugo',
      nota: 'Irregular. Buena presencia física pero error grave en el segundo gol rival. Pierde concentración en transiciones rápidas. En evaluación.',
      valoracion: 5,
      createdAt: '2025-01-30T21:00:00Z',
    },
  ],
  'demo-5': [
    {
      id: 'dv-5-1',
      fecha: '2025-03-15',
      partido: 'J28 · Granada CF B vs Almería B',
      nota: 'Excelente partido. Desbordó en 7 de 8 intentos registrados. Gol y asistencia. Presencia física mayor de lo esperado para su talla. Promesa total.',
      valoracion: 9,
      createdAt: '2025-03-15T21:00:00Z',
    },
    {
      id: 'dv-5-2',
      fecha: '2025-02-01',
      partido: 'J21 · UD Almería B vs Granada CF B',
      nota: 'Partido más difícil fuera de casa. Corrió mucho pero poco efectivo en el último cuarto del campo. Pierde el balón en el cara a cara.',
      valoracion: 6,
      createdAt: '2025-02-01T21:00:00Z',
    },
  ],
  'demo-6': [
    {
      id: 'dv-6-1',
      fecha: '2025-02-14',
      partido: 'J22 · Valencia CF Mestalla vs Eldense CF',
      nota: 'Portero con buenas condiciones pero actitud problemática durante el partido. Tensión con compañeros y con el colegiado. No encaja en el perfil buscado.',
      valoracion: 5,
      createdAt: '2025-02-14T21:00:00Z',
    },
  ],
};

// ─── Demo Matches (Scout Log) ─────────────────────────────────────────────────

export const DEMO_MATCHES: Match[] = [
  {
    id: 'dm-1',
    date: '2025-03-29',
    competition: 'Segunda División',
    category: 'Profesional',
    homeTeam: 'RC Deportivo',
    awayTeam: 'SD Ponferradina',
    result: '2-0',
    venue: 'Estadio Abanca-Riazor',
    notes: 'Partido de alta intensidad. Deportivo dominó en la segunda mitad. Ruano destacó como lateral derecho.',
    linkedPlayers: ['demo-3'],
    userId: 'demo',
    createdAt: '2025-03-29T20:00:00Z',
    updatedAt: '2025-03-29T22:00:00Z',
  },
  {
    id: 'dm-2',
    date: '2025-03-22',
    competition: 'Primera RFEF',
    category: 'Nacional',
    homeTeam: 'Atlético Baleares',
    awayTeam: 'UD Ibiza',
    result: '3-1',
    venue: 'Estadio Balear',
    notes: 'Diego Morales fue el mejor del partido. Partido de alta calidad técnica. Ambiente excelente.',
    linkedPlayers: ['demo-2'],
    userId: 'demo',
    createdAt: '2025-03-22T19:30:00Z',
    updatedAt: '2025-03-22T22:00:00Z',
  },
  {
    id: 'dm-3',
    date: '2025-03-15',
    competition: 'Segunda RFEF Grupo IV',
    category: 'Nacional',
    homeTeam: 'Sevilla FC B',
    awayTeam: 'Recreativo Huelva',
    result: '2-2',
    venue: 'Ciudad Deportiva José Ramón Cisneros Palacios',
    notes: 'Vistazo a Carlos Vega y Sergio Linares en el mismo partido. Los dos respondieron bien.',
    linkedPlayers: ['demo-1', 'demo-5'],
    userId: 'demo',
    createdAt: '2025-03-15T19:00:00Z',
    updatedAt: '2025-03-15T22:00:00Z',
  },
  {
    id: 'dm-4',
    date: '2025-03-08',
    competition: 'Primera RFEF',
    category: 'Nacional',
    homeTeam: 'CD Lugo',
    awayTeam: 'Sporting Gijón B',
    result: '1-0',
    venue: 'Estadio Municipal de A Xunqueira',
    notes: 'Seguimiento de Javier Soto. Partido físico y muy disputado. Buenas condiciones meteorológicas.',
    linkedPlayers: ['demo-4'],
    userId: 'demo',
    createdAt: '2025-03-08T20:00:00Z',
    updatedAt: '2025-03-08T22:00:00Z',
  },
];

// ─── Demo Alerts ─────────────────────────────────────────────────────────────

export const DEMO_ALERTS: Alert[] = [
  {
    id: 'da-1',
    playerId: 'demo-1',
    date: '2025-04-30',
    message: 'Renovar seguimiento de Carlos Vega antes del mercado de verano',
    priority: 'urgent',
    done: false,
    createdAt: '2025-03-16T10:00:00Z',
  },
  {
    id: 'da-2',
    playerId: 'demo-2',
    date: '2025-05-15',
    message: 'Concertar entrevista con el agente de Diego Morales',
    priority: 'warning',
    done: false,
    createdAt: '2025-03-23T09:00:00Z',
  },
  {
    id: 'da-3',
    playerId: 'demo-5',
    date: '2025-04-26',
    message: 'Visita planificada: Granada CF B vs Almería B — Jornada 34',
    priority: 'info',
    done: false,
    createdAt: '2025-03-15T22:00:00Z',
  },
];
